[build]
  base = "brigette-chomali-photography"
  publish = "brigette-chomali-photography"
  functions = "brigette-chomali-photography/netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
